CREATE TABLE Users (
    UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Stocks (
    StockId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Symbol VARCHAR(32) NOT NULL,
    ShortName VARCHAR(255),
    LongName VARCHAR(255),
    Sector VARCHAR(255),
    Industry VARCHAR(255)
);

CREATE TABLE Preferences (
    PreferenceId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    StockId INT NOT NULL,
    PreferencesList TEXT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (StockId) REFERENCES Stocks(StockId) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX (UserId)
);